### ISSUE TITLE
Doesn't seem to be working on 2.5

### ISSUE THREAD

**Issue by Anahkiasen** [atomicptr/Cyberduck-Favorites#1]
I don't know if it was working before as this hasn't been updated in a while but on 2.5 whether I try "connect" or "ftp" it always fallbacks to the standard search.

**Comment by atomicptr** [comment]
It's working fine for me...

Could you please open a terminal in the directory where your "Cyberduck Favorites" workflow is and run this command:

```
python cyberduck.py
```

**Comment by lwatiker** [comment]
Hi Kasoki, thanks for putting this workflow together!

I'm getting a similar issue and would love to help you debug it.
I ran `python cyberduck.py` and am still having the issue.

I tried running the workflow with the bug reporter in alfred open and recieved the following error dump:

```
Starting debug for 'Cyberduck Favorites'

[ERROR: alfred.workflow.input.scriptfilter] Code 0: Traceback (most recent call last):
  File "cyberduck.py", line 71, in <module>
    handler.push()
  File "/Users/lwatiker/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.6F4B97EF-0A90-4F9F-A6F4-650D8D535498/Alfred.py", line 118, in push
    print self.to_xml(max_results)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 198: ordinal not in range(128)
[ERROR: alfred.workflow.input.scriptfilter] Code 0: Traceback (most recent call last):
  File "cyberduck.py", line 71, in <module>
    handler.push()
  File "/Users/lwatiker/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.6F4B97EF-0A90-4F9F-A6F4-650D8D535498/Alfred.py", line 118, in push
    print self.to_xml(max_results)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 198: ordinal not in range(128)
[ERROR: alfred.workflow.input.scriptfilter] Code 0: Traceback (most recent call last):
  File "cyberduck.py", line 71, in <module>
    handler.push()
  File "/Users/lwatiker/Library/Application Support/Alfred 2/Alfred.alfredpreferences/workflows/user.workflow.6F4B97EF-0A90-4F9F-A6F4-650D8D535498/Alfred.py", line 118, in push
    print self.to_xml(max_results)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2013' in position 198: ordinal not in range(128)
```

**Comment by atomicptr** [comment]
I want the output from `python cyberduck.py` :)

**Comment by lwatiker** [comment]
Can do!
 (Sorry its on one line)

```
<?xml version="1.0" encoding="UTF-8" ?><items><item uid="None" arg="/Users/lwatiker/Library/Application Support/Cyberduck/Bookmarks/13436dbd-cb9c-433e-b72b-a92e4c62c54a.duck"><title>docs.google.com – Google Docs</title><subtitle>GD lwatiker@gmail.com@docs.google.com:443</subtitle><icon>bookmark_icon.png</icon></item><item uid="None" arg="/Users/lwatiker/Library/Application Support/Cyberduck/Bookmarks/195a2e84-207b-4363-9936-fb55ec8f42fa.duck"><title>CS Grading</title><subtitle>SFTP lwatiker@cs.oberlin.edu:22</subtitle><icon>bookmark_icon.png</icon></item><item uid="None" arg="/Users/lwatiker/Library/Application Support/Cyberduck/Bookmarks/5979bbcf-385d-4fd8-b2b1-904389bd37b6.duck"><title>Oberlin CS</title><subtitle>SFTP lwatiker@cs.oberlin.edu:22</subtitle><icon>bookmark_icon.png</icon></item><item uid="None" arg="/Users/lwatiker/Library/Application Support/Cyberduck/Bookmarks/67ee23ae-29d2-4e03-a260-7622795a3042.duck"><title>Amazon S3 (HTTPS)</title><subtitle>S3 lwatiker@s3.amazonaws.com:443</subtitle><icon>bookmark_icon.png</icon></item><item uid="None" arg="/Users/lwatiker/Library/Application Support/Cyberduck/Bookmarks/890096c3-96ac-4fdf-b3c7-ee79c6f09d69.duck"><title>cs.oberlin.edu – SFTP</title><subtitle>SFTP lwatiker@cs.oberlin.edu:22</subtitle><icon>bookmark_icon.png</icon></item><item uid="None" arg="/Users/lwatiker/Library/Application Support/Cyberduck/Bookmarks/a9f546ba-7c5f-4f58-b735-d1b4820c4f27.duck"><title>Rackspace Cloud Files</title><subtitle>CF lwatiker@storage.clouddrive.com:443</subtitle><icon>bookmark_icon.png</icon></item><item uid="None" arg="/Users/lwatiker/Library/Application Support/Cyberduck/Bookmarks/c21ad5af-34e1-43ce-9986-6d103f6506e5.duck"><title>EC2 Server</title><subtitle>SFTP ubuntu@ec2-174-129-141-9.compute-1.amazonaws.com:22</subtitle><icon>bookmark_icon.png</icon></item></items>
```

**Comment by atomicptr** [comment]
Very strange, it should work... please try to remove the `–` character from the title of your bookmarks.

Seems that Alfred isn't very happy with this non-ascii character

**Comment by lwatiker** [comment]
Good catch! I removed the offending bookmarks and it works great now.
Thanks for your help!

**Comment by edheltzel** [comment]
Still not working for me:

```
Traceback (most recent call last):
  File "cyberduck.py", line 55, in <module>
    username = info["values"][i]
IndexError: list index out of range
```

**Comment by edheltzel** [comment]
@kasoki So I went into your `cyberduck.py` file and ended up commenting out Lines **54** and **55** to get the workflow working again -- based on the debug info from Alfred. I know this is not ideal... 

``` python
    for key in info["keys"]:
        if key == "Nickname":
            nickname = info["values"][i]
        # elif key == "Username":
        #   username = info["values"][i]
        elif key == "Port":
            port = info["values"][i]
        elif key == "Protocol":
            protocol = info["values"][i]
        elif key == "Hostname":
            hostname = info["values"][i]

        i += 1
```
